name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - 1.40.0
        features:
          - ""
          - --features skeptic_tests
          - --features logging
          - --features skeptic_tests logging
          - --no-default-features
          - --no-default-features --features skeptic_tests
          - --no-default-features --features logging
          - --no-default-features --features skeptic_tests logging
          - --features clippy

    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: core crate
        run: |
          cd derive_builder_core
          cargo build ${{ matrix.features }} --verbose
          cargo test --no-fail-fast ${{ matrix.features }} --verbose -- --nocapture
          cargo doc

      - name: macro crate
        run: |
          cd derive_builder_macro
          cargo build ${{ matrix.features }} --verbose
          cargo test --no-fail-fast ${{ matrix.features }} --verbose -- --nocapture
          cargo doc

      - name: main crate
        run: |
          cd derive_builder
          cargo build ${{ matrix.features }} --verbose
          cargo test --no-fail-fast ${{ matrix.features }} --verbose -- --nocapture
          cargo doc
